version: '3.2'
services:
    server:
      restart: always
      command : bash -c "python manage.py makemigrations &&
                python manage.py migrate &&
                python manage.py runserver 0.0.0.0:8000"
      build:
        dockerfile: Dockerfile
        context: ./auth_server
      ports:
        - '8000:8000'
    
    client:
      restart: always
      command : npm start 
      build:
        dockerfile: Dockerfile
        context: ./auth_client
      ports:
        - '3000:3000'
      environment:
      - REACT_APP_SERVER_API=http://localhost:8000/api